### ISSUE TITLE
Trouble accessing Nbuff for vibe.d TCP read call

### ISSUE THREAD

**Issue by kookman** [ikod/nbuff#1]
Nbuff looks to be a great solution to improving the buffer handling for my (vibe.d based) Nats client. However, I am having trouble determining from the doc's and unit tests why the below code fails to compile:
```d
                auto readBuffer = Nbuff.get(readSize);
                pragma(msg,"readBuffer.data: ", typeof(readBuffer.data));
                immutable bytesRead = _conn.read(readBuffer.data, IOMode.once);
                _bytesReceived += bytesRead;
                // convert to immutable buffer and process
                auto natsProtocolChunk = NbuffChunk(readBuffer, bytesRead);
                buffer.append(natsProtocolChunk);
```

At compile time I get:
```Performing "debug" build using dmd for x86_64.
nats 0.2.6: building configuration "lib"...
readBuffer.data: ubyte[]
src/nats/client.d(344,60): Error: no property `data` for type `nbuff.buffer.UniquePtr!(MutableMemoryChunk)`
```

So although the pragma outputs the type I'd expect (`ubyte[]`), for some reason, the data method/property is hidden when trying to call `read` on it.

**Comment by kookman** [comment]
BTW, there are references in the Readme and at the top of `nbuff/buffer.d` to a `Buffer` type. Was this just renamed to Nbuff, or is there another type that should be included here?

**Comment by ikod** [comment]
Hello, @kookman 

Let me see... Will come back

**Comment by ikod** [comment]
Well,
This simple test compiles and works for me as expected:
```d
import std.stdio;
import vibe.vibe;
import nbuff;

void main()
{
    auto conn = connectTCP("time-c.nist.gov", 13);
    auto readBuffer = Nbuff.get(1024);
    immutable bytesRead = conn.read(readBuffer.data, IOMode.once);
    writeln(cast(string)readBuffer.data);
}
```
```shell
Running ./nbufftest 

59337 21-05-03 09:15:30 50 0 0 434.0 UTC(NIST) * 
$ dmd --version
DMD64 D Compiler v2.094.0

```

Here is my dub.selection.json:
```json
{
	"fileVersion": 1,
	"versions": {
		"automem": "0.6.4",
		"botan": "1.12.19",
		"botan-math": "1.0.3",
		"diet-ng": "1.7.5",
		"eventcore": "0.9.13",
		"ikod-containers": "0.0.20+commit.7.g6c6ec8f",
		"libasync": "0.8.6",
		"memutils": "1.0.4",
		"mir-linux-kernel": "1.0.1",
		"nbuff": "0.1.12",
		"openssl": "1.1.6+1.0.1g",
		"stdx-allocator": "2.77.5",
		"taggedalgebraic": "0.11.20",
		"test_allocator": "0.3.3",
		"unit-threaded": "0.10.8",
		"vibe-core": "1.16.0",
		"vibe-d": "0.9.3"
	}
}
```
What is your package/compiler versions? Also you can try to build a minimal code to reproduce problem, I'll try to investigate.

Anyway: you can try workaround this problem with something like this:

```d
    auto readBuffer = Nbuff.get(1024);
    auto bufferData = readBuffer.data();
    immutable bytesRead = conn.read(bufferData, IOMode.once);
```
maybe there is some 'interference' between uniquePtr and MutableBuffer

Don;t hesitate to contact me in case of problems

**Comment by ikod** [comment]
> BTW, there are references in the Readme and at the top of `nbuff/buffer.d` to a `Buffer` type. Was this just renamed to Nbuff, or is there another type that should be included here?

This is bug in README, will fix it. Buffer is my old name for Nbuff, thanks for report

**Comment by kookman** [comment]
Still investigating this (did not get much time today). But your test program compiles & works in my setup too:
```d
/+ dub.sdl:
name "test"
dependency "vibe-d" version="~>0.9"
dependency "nbuff" version="~>0.1"
+/

import std.stdio;
import vibe.vibe;
import nbuff;

void main()
{
        auto conn = connectTCP("time-c.nist.gov", 13);
        auto readBuffer = Nbuff.get(1024);
        immutable bytesRead = conn.read(readBuffer.data, IOMode.once);
        writeln(cast(string)readBuffer.data);
}
```

Compiler version (macOS environment):
```
sydmacr1uj:~/code/github/nats(master⚡) » dmd --version
DMD64 D Compiler v2.096.0

Copyright (C) 1999-2021 by The D Language Foundation, All Rights Reserved written by Walter Bright
```

**Comment by kookman** [comment]
But the original code still failing. Even with the workaround to separate the .data() reference to another local.

```d
            if (result == WaitForDataStatus.dataAvailable)
            {
                auto readBuffer = Nbuff.get(readSize);
                auto readBufferData = readBuffer.data();
                pragma(msg,"readBuffer.data: ", typeof(readBufferData));
                immutable bytesRead = _conn.read(readBufferData, IOMode.once);
```

```
Performing "debug" build using dmd for x86_64.
nats 0.2.6: building configuration "lib"...
src/nats/client.d(343,49): Error: no property `data` for type `nbuff.buffer.UniquePtr!(MutableMemoryChunk)`
readBuffer.data: _error_
```

It does seem like something is interfering with the compiler resolving the reference to Nbuff.data() method. I will keep looking into this tomorrow. Thanks for your help so far.

**Comment by ikod** [comment]
hello, @kookman 

If I can clone this problem code from some branch of your repo, I can test it too.

**Comment by kookman** [comment]
thanks @ikod. I am away from my development machine right now, but I will push the code to a branch tomorrow and send you a link.

**Comment by kookman** [comment]
Ok, so I'm still stuck. I've pushed my work to my repo as the branch nbuff:
[https://github.com/kookman/nats/tree/nbuff](https://github.com/kookman/nats/tree/nbuff)
The snippet that I was pasting before is in the method `listener()` in `src/nats/client.d`. https://github.com/kookman/nats/blob/ff34c97dcc651b78893827b2772c92b5dd04c080/src/nats/client.d#L342

The compiler output I get is:
```
Performing "debug" build using dmd for x86_64.
nats 0.2.6: building configuration "lib"...
src/nats/client.d(343,49): Error: no property `data` for type `nbuff.buffer.UniquePtr!(MutableMemoryChunk)`
readBuffer.data: _error_
src/nats/client.d(350,51): Error: function `nats.client.Nats.processNatsStream(return scope const(ubyte)[] response)` is not callable using argument types `(NbuffChunk)`
src/nats/client.d(350,51):        cannot pass argument `buffer.data()` of type `NbuffChunk` to parameter `return scope const(ubyte)[] response`
dmd failed with exit code 1.
```

**Comment by kookman** [comment]
Thanks @ikod for the documentation updates. Based on that, I've made some further pushes to the nbuff branch in my repo, now using .pop() method to free up consumed buffers. 

It does raise a question for me: I notice you mentioned that chunks in the buffer are not necessarily stored continguously. I have made assumption that I can just slice parts of the message into a scope struct (Msg) for processing, and that this would be fine as long as lifetime of Msg is completed before the call to Nbuff.pop() However, it seems from reading your new documentation that just slicing might be invalid if the message data crosses nbuff chunk boundaries. Is my understanding correct?

**Comment by ikod** [comment]
> Thanks @ikod for the documentation updates. Based on that, I've made some further pushes to the nbuff branch in my repo, now using .pop() method to free up consumed buffers.
> 
> It does raise a question for me: I notice you mentioned that chunks in the buffer are not necessarily stored continguously. I have made assumption that I can just slice parts of the message into a scope struct (Msg) for processing, and that this would be fine as long as lifetime of Msg is completed before the call to Nbuff.pop() However, it seems from reading your new documentation that just slicing might be invalid if the message data crosses nbuff chunk boundaries. Is my understanding correct?

Everythihg here should be better documented.

Nbuff itself has chain of memory chunks as backing store.

https://github.com/ikod/nbuff/blob/master/source/nbuff/buffer.d#L1353
Nbuff.data(a, b) returns NbuffChunk which has contiguous data backstore. It is possible that it will copy some part of data to make it contiguous. But if [a,b] points inside a contiguous chunk, then there will be no data copy.

Example
```d
Nbuff b;
b.append("0123");
b.append("4567");
auto c = b.data(0, 3); // <- shared reference to contiguous backstore, no data copy involved
auto c_data = c.data(); // <- @system access to contiguous backstore, this have to be embraced with @trusted block
auto d = b.data(0,8); // <- shared reference to contiguous backstore, require data copy
auto d_data = d.data();
```
in each case Nbuff.data(a,b) gives you smart ptr to contiguous data, which you dereference to real contiguous memory slice with one more data() call.

From the other side you can completely avoid data copy using Nbuff.frontChunk() but then you can receive  can have incomplete data.

**Comment by ikod** [comment]
> Ok, so I'm still stuck. I've pushed my work to my repo as the branch nbuff:
> https://github.com/kookman/nats/tree/nbuff
> The snippet that I was pasting before is in the method `listener()` in `src/nats/client.d`. https://github.com/kookman/nats/blob/ff34c97dcc651b78893827b2772c92b5dd04c080/src/nats/client.d#L342
> 
> The compiler output I get is:
> 
> ```
> Performing "debug" build using dmd for x86_64.
> nats 0.2.6: building configuration "lib"...
> src/nats/client.d(343,49): Error: no property `data` for type `nbuff.buffer.UniquePtr!(MutableMemoryChunk)`
> readBuffer.data: _error_
> src/nats/client.d(350,51): Error: function `nats.client.Nats.processNatsStream(return scope const(ubyte)[] response)` is not callable using argument types `(NbuffChunk)`
> src/nats/client.d(350,51):        cannot pass argument `buffer.data()` of type `NbuffChunk` to parameter `return scope const(ubyte)[] response`
> dmd failed with exit code 1.
> ```
```
diff --git a/src/nats/client.d b/src/nats/client.d
index 9b0dc44..8b5391d 100644
--- a/src/nats/client.d
+++ b/src/nats/client.d
@@ -340,14 +340,14 @@ final class Nats
             if (result == WaitForDataStatus.dataAvailable)
             {
                 auto readBuffer = Nbuff.get(readSize);
-                auto readBufferData = readBuffer.data();
-                pragma(msg,"readBuffer.data: ", typeof(readBufferData));
+                auto readBufferData = () @trusted {return readBuffer.data();}();
+                pragma(msg,"readBuffer.data: ", typeof(readBuffer));
                 immutable bytesRead = _conn.read(readBufferData, IOMode.once);
                 _bytesReceived += bytesRead;
                 // convert to immutable buffer and process
                 auto natsProtocolChunk = NbuffChunk(readBuffer, bytesRead);
                 buffer.append(natsProtocolChunk);
-                auto consumed = processNatsStream(buffer.data());
+                auto consumed = () @trusted {return processNatsStream(buffer.data().data());}();
                 version (NatsClientLogging) {
                     if (consumed < buffer.length)
                         logTrace("Fragment (length: %s) left in buffer. Consolidating with another read.", buffer.length - consumed);
```

This fixes problem. calls to data() have to be wrapped with @trusted as you get access to underlying memory. As data() implemented using opDispatch for UniquePtr you don't get clear error message, alas.

**Comment by kookman** [comment]
Thanks @ikod! This was a nice find. I didn't consider trying to annotate the reduced test function @safe.

Also, good to have the clue on doubling up on the .data() to go from Nbuff -> NbuffChunk -> ubyte[].

Closing this issue.

**Comment by ikod** [comment]
Hello @kookman 

nice to hear that this helped.
If you decide to move forward with nbuff - let me know about problems.

**Comment by kookman** [comment]
hi @ikod I just wanted to let you know that the new Nbuff based version of my Nats client has passed stress tests without any memory leaks or corruption detected. Apart from a few problems stemming from my misunderstanding how to use the API at first, this has been a trouble-free experience.
Thanks for the library!

**Comment by ikod** [comment]
Hi, @kookman 

> hi @ikod I just wanted to let you know that the new Nbuff based version of my Nats client has passed stress tests without any memory leaks or corruption detected. Apart from a few problems stemming from my misunderstanding how to use the API at first, this has been a trouble-free experience.
> Thanks for the library!

Thanks for sharing this! Very nice to know!

**Comment by ikod** [comment]
Hello @kookman 

I prepared small tutorial: https://github.com/ikod/nbuff/blob/master/docs/tutorial-e.md

It will be great if you will be so kind to fix (google) translation :)

**Comment by kookman** [comment]
Hi @ikod, the document looks pretty good for a google translate! I made some very minor edits in PR #2 

Thanks for this - I think it will make the library easier for newcomers (it would certainly have helped me when I started).

**Comment by ikod** [comment]
Thanks for your contribution, @kookman !
