### ISSUE TITLE
How does Nbuff keep threads safe through multi-threaded calls?

### ISSUE THREAD

**Issue by zoujiaqing** [ikod/nbuff#6]
As the headline says ;)

**Comment by ikod** [comment]
> As the headline says ;)

Nbuff is not thread safe. Maybe you can have access to data from different threads, but Nbuff itself and pools are not thread-safe

**Comment by zoujiaqing** [comment]
How can we make each thread use a separate Nbuff object?

**Comment by ikod** [comment]
What is your usecase?


ср, 11 мая 2022 г., 12:56 zoujiaqing ***@***.***>:

**Comment by zoujiaqing** [comment]
I developed a completely new HTTP framework.

### Archttp
https://github.com/kerisy/archttp

### Example
examples/httpserver/

There were no problems in single-threaded mode and stress tests were performed correctly with WRK.
A problem occurred in multithreaded mode.
Change `ioThreads` in the test code to a number greater than 1 to enable multithreading.

**Comment by ikod** [comment]
Ok, will see today

ср, 11 мая 2022 г., 14:18 zoujiaqing ***@***.***>:

**Comment by ikod** [comment]
Hello, @zoujiaqing 

I'm digging through the code. As far as I can see you have separate io threads and separate worker threads and you read data from network in io thread. If you attach data to nbuffs in io thread and then send nbuffs to workers threads - this will not work.

**Comment by zoujiaqing** [comment]
OK!

It seems to be working pretty well, right?

```bash
git clone https://github.com/kerisy/archttp.git
cd archttp/examples/httpserver/
dub run
```

**Comment by ikod** [comment]
hello @zoujiaqing 
```
$ wrk -d 60 -c 200 -t 5 http://127.0.0.1:8080/
Running 1m test @ http://127.0.0.1:8080/
  5 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.88ms    2.01ms  26.03ms   86.23%
    Req/Sec    28.70k     4.85k   34.81k    68.47%
  8566910 requests in 1.00m, 0.92GB read
Requests/sec: 142778.69
Transfer/sec:     15.66MB
```

looks very good!

You combined io and worker threads in single thread?

**Comment by zoujiaqing** [comment]
Currently, it is bound to IO and worker. The future will be broken up.

**Comment by ikod** [comment]
hello @zoujiaqing 

ok, I will close this issue now. If you will need some support from nbuff in the future - feel free to post new issue.
